### ISSUE TITLE
Subscribe problems (trought websocket-nats)

### ISSUE THREAD

**Issue by shubinmi** [orus-io/nats-websocket-gw#1]
Hi, thank you for this library at first! I tried it with js ("websocket-nats") on the front side. Publish functional works is ok, but subscribe does not for me. It looks like proxy sends data from "front-end" to "NATS server" only. Do you have some ideas or examples?

**Comment by cdevienne** [comment]
I only tested with elm-nats, so I do not have an example with websocket-nats.

However it should work.

Could you be more precise about what is not working:
- When you initialize the subscription, do you have any error message?
- Do you have any logs on the proxy when a message is supposed to fly back to a front subscription?
- Ideally, could you check if you have the same behavior with https://github.com/isobit/ws-tcp-relay?

**Comment by shubinmi** [comment]
I do not get any error msg. I have checked with "https://github.com/isobit/ws-tcp-relay" and it works fine.

**Comment by cdevienne** [comment]
This is weird... I will do some tests.

**Comment by cdevienne** [comment]
I reproduced the issue.
The incoming MSG is sent back by the gateway, it is received by websocket-nats, but the subscription handler is not called... very strange.
Looking into it.

**Comment by cdevienne** [comment]
Hi @shubinmi 

Could you test the latest version?

Thanks for reporting the issue.

**Comment by shubinmi** [comment]
Thank you a lot! Great job, it is ok now 👍
