### ISSUE TITLE
Publish binary data

### ISSUE THREAD

**Issue by mmardinian** [orus-io/nats-websocket-gw#3]
Hi,

I try to transfert binary buffer to a Nats client using our gateway and websocket-nats.
But binary data don't seems to be handled well.
I get some "EOF" messages which seems to be related to a string format.

Could you tell me how to configure the connection beween websocket-nats and your gateway in binary please?

Thanks.
Michael

**Comment by mmardinian** [comment]
Please, find the logs. each frame is sent every 400ms for now.

[TRACE] --> PUB system.audio.raop_output.Room1.local.writeStream 1024
[object ArrayBuffer]

[TRACE] --> PUB system.audio.raop_output.Room1.local.writeStream 1024
[object ArrayBuffer]

[TRACE] --> PUB system.audio.raop_output.Room1.local.writeStream 1024
[object ArrayBuffer]

[TRACE] --> PUB system.audio.raop_output.Room1.local.writeStream 1024
[object ArrayBuffer]

[TRACE] --> PUB system.audio.raop_output.Room1.local.writeStream 1024
[object ArrayBuffer]

[TRACE] --> PUB system.audio.raop_output.Room1.local.writeStream 1024
[object ArrayBuffer]

[TRACE] --> PUB system.audio.raop_output.Room1.local.writeStream 1024
[object ArrayBuffer]

[TRACE] --> PUB system.audio.raop_output.Room1.local.writeStream 1024
[object ArrayBuffer]

[TRACE] --> PUB system.audio.raop_output.Room1.local.writeStream 1024
[object ArrayBuffer]

[TRACE] --> PUB system.audio.raop_output.Room1.local.writeStream 1024
[object ArrayBuffer]

[TRACE] --> PUB system.audio.raop_output.Room1.local.writeStream 1024
[object ArrayBuffer]

[TRACE] --> PUB system.audio.raop_output.Room1.local.writeStream 1024
[object ArrayBuffer]

[TRACE] --> PUB system.audio.raop_output.Room1.local.writeStream 1024
[object ArrayBuffer]

[TRACE] <-- -ERR 'Unknown Protocol Operation'

[ERROR] EOF
[ERROR] read tcp 10.0.140.56:8910->10.0.140.211:55553: use of closed network connection

**Comment by cdevienne** [comment]
Hi @mmardinian, 

I implemented binary mode support in the 'binary-message-support' branch.
To enable it, add '?mode=binary' to the URL.
Could you give it a try ?

**Comment by mmardinian** [comment]
Hi Christophe.
Thank you for your support.
Here is what I've done:
`var nats_path = 'ws://' + location.hostname + ':8910/nats?mode=binary';`
`var nats = NATS.connect({ 'url':nats_path, 'preserveBuffers': true});`

It does not change a thing for now, but I get this weird error in my browser logs when I add this option:
`Uncaught TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (websocket-nats.js:1562)
    at from (websocket-nats.js:1388)
    at new Buffer (websocket-nats.js:1364)
    at WebSocket.<anonymous> (websocket-nats.js:3550)`

**Comment by cdevienne** [comment]
I guess websocket-nats.js needs adaptation too then.

**Comment by mmardinian** [comment]
Yes indeed, type requested was Int8Array.
https://github.com/isobit/websocket-nats/issues/4#issuecomment-261478577

works like a charm, thank you

**Comment by cdevienne** [comment]
branch merged, thanks for testing.
