### ISSUE TITLE
Using Nats authentification

### ISSUE THREAD

**Issue by mmardinian** [orus-io/nats-websocket-gw#4]
Hi,

I upgraded my Nats server with authentification system.
But that doesn't work with nats-websocket-gw.

Instead of providing a standard nats path: "localhost:1234"
I added the user and password info: "[john:doe@localhost]:21400"
(braquets are added following this rule: https://socketloop.com/tutorials/golang-dial-tcp-too-many-colons-in-address)

But this bring also in issue with dial tcp:
`[ERROR] dial tcp: lookup john:doe@localhost: no such host`

Is there another way to pass credentials information for Nats?

Thanks

**Comment by cdevienne** [comment]
The credentials should be passed by the final client, in the initial CONNECT command.
 
Il you embed nats-websocket-gw into your own program, you can override this phase and let the gateway intercept the CONNECT command and do the authentication instead of the client.

**Comment by mmardinian** [comment]
whow, you're reactive.
ok, I should have given a little bit more information.

On nats-websocket-gw side, instead of doing this:
`gateway := gw.NewGateway(gw.Settings{
		NatsAddr: "localhost:4222",
	})`

I've done this:
`gateway := gw.NewGateway(gw.Settings{
		NatsAddr: "[john:doe@localhost]:21400",
	})`

Is it what you mean?

**Comment by cdevienne** [comment]
No its not ^^

You have two possibilities. 

1) the user/password are known by the final client:

- Keep ``gateway := gw.NewGateway(gw.Settings{ NatsAddr: "localhost:4222", })``, and on the client side, for example the javascript lib, do something like this:
```
var nats = NATS.connect({user: "john", password: "doe"});
```

2) The user/password must be handled by the gateway
In this case, the gateway has to intercept the CONNECT sent by the client and forge its own instead. This can be done by defining a custom ConnectHandler (the default implementation is here: https://github.com/orus-io/nats-websocket-gw/blob/master/gw.go#L54)

Something like this, which is taken from https://bitbucket.org/orus-io/xbus/src/2aea64abceae99caa33b440a4f76da3486198b7f/cmd/xbus-http/cmd/serve.go#lines-102 :

```go
gateway := gw.NewGateway(gw.Settings{
	NatsAddr: "localhost:4222",

	ConnectHandler: func(natsConn *gw.NatsConn, r *http.Request, ws *websocket.Conn) error {
		// send the server info
		infoCmd := bytes.Join([][]byte{
			[]byte("INFO "),
			[]byte(natsConn.ServerInfo),
			[]byte("\r\n"),
		}, nil)
		if err := ws.WriteMessage(websocket.TextMessage, infoCmd); err != nil {
			return err
		}

		// wait for the CONNECT from the client
		_, connectCmd, err := ws.ReadMessage()
		if err != nil {
			return err
		}

		splitted := bytes.SplitN(connectCmd, []byte(" "), 2)
		if len(splitted) != 2 {
			return fmt.Errorf("Invalid command: '%s'", connectCmd)
		}

		if !bytes.Equal(splitted[0], []byte("CONNECT")) {
			if bytes.Equal(splitted[0], []byte("-ERR")) {
				ws.WriteMessage(websocket.TextMessage, connectCmd)
				return fmt.Errorf(
					"Server returned an error: %s",
					connectCmd)
			}
			return fmt.Errorf(
				"Invalid command. Expected 'CONNECT', got: %s",
				connectCmd)
		}

		var connectDict map[string]interface{}
		if err := json.Unmarshal(
			splitted[1][:len(splitted[1])-2],
			&connectDict,
		); err != nil {
			return nil
		}

		// inject credentials
		connectDict["user"] = "john"
		connectDict["user"] = "doe"

		// drop unauthorized auth values
		delete(connectDict, "auth_token")
		delete(connectDict, "jwt")
		delete(connectDict, "sig")

		cmd, err := json.Marshal(connectDict)
		if err != nil {
			return err
		}
		// pass it on
		cmd = bytes.Join([][]byte{
			[]byte("CONNECT "), cmd, []byte("\r\n"),
		}, nil)
		_, err = natsConn.Conn.Write(cmd)
		return err
	},
})

```

**Comment by mmardinian** [comment]
Ok I had it all wrong.
1st possibility seems to work as a charm.

Thank you
